---
abstract: '根据 Kossy 中的 Validator 移植过来的模块'
author:
  - 'fukai <iakuf@163.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-KossyValidator
no_index:
  directory:
    - t
    - inc
requires:
  Dancer: 1.3
version: 0.01
